// fetch All catagory request types
export const GET_ALL_CATAGOTY_REQUEST = "GET_ALL_CATAGOTY_REQUEST";
export const GET_ALL_CATAGORY_SUCCESS = "GET_ALL_CATAGORY_SUCCESS";
export const GET_ALL_CATAGORY_FAILURE = "GET_ALL_CATAGORY_FAILURE";

export const GET_CURRENT_CATAGOTY_REQUEST = "GET_CURRENT_CATAGOTY_REQUEST";
export const GET_CURRENT_CATAGORY_SUCCESS = "GET_CURRENT_CATAGORY_SUCCESS";
export const GET_CURRENT_CATAGORY_FAILURE = "GET_CURRENT_CATAGORY_FAILURE";

export const HANDLE_CATEGORY_MODAL = "HANDLE_CATEGORY_MODAL";
export const UPDATE_CATEGORY_MODAL = "UPDATE_CATEGORY_MODAL";

export const ADD_CATAGORY_REQUEST = "ADD_CATAGORY_REQUEST";
export const ADD_CATAGORY_SUCCESS = "ADD_CATAGORY_SUCCESS";
export const ADD_CATAGORY_FAILURE = "ADD_CATAGORY_FAILURE";

export const UPDATE_CATAGORY_REQUEST = "UPDATE_CATAGORY_REQUEST";
export const UPDATE_CATAGORY_SUCCESS = "UPDATE_CATAGORY_SUCCESS";
export const UPDATE_CATAGORY_FAILURE = "UPDATE_CATAGORY_FAILURE";
